//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreTerra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoreTerra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Adamantite {
            get {
                object obj = ResourceManager.GetObject("Adamantite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Altar {
            get {
                object obj = ResourceManager.GetObject("Altar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Amethyst {
            get {
                object obj = ResourceManager.GetObject("Amethyst", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArmsDealer {
            get {
                object obj = ResourceManager.GetObject("ArmsDealer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Barrel {
            get {
                object obj = ResourceManager.GetObject("Barrel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigCannon {
            get {
                object obj = ResourceManager.GetObject("BigCannon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Cannon {
            get {
                object obj = ResourceManager.GetObject("Cannon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chest {
            get {
                object obj = ResourceManager.GetObject("Chest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chlorophyte {
            get {
                object obj = ResourceManager.GetObject("Chlorophyte", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Clothier {
            get {
                object obj = ResourceManager.GetObject("Clothier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cobalt {
            get {
                object obj = ResourceManager.GetObject("Cobalt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Containers {
            get {
                object obj = ResourceManager.GetObject("Containers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copper {
            get {
                object obj = ResourceManager.GetObject("Copper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CorruptionChest {
            get {
                object obj = ResourceManager.GetObject("CorruptionChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CrimsonChest {
            get {
                object obj = ResourceManager.GetObject("CrimsonChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crimtane {
            get {
                object obj = ResourceManager.GetObject("Crimtane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cyborg {
            get {
                object obj = ResourceManager.GetObject("Cyborg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Demolitionist {
            get {
                object obj = ResourceManager.GetObject("Demolitionist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Demonite {
            get {
                object obj = ResourceManager.GetObject("Demonite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Diamond {
            get {
                object obj = ResourceManager.GetObject("Diamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dryad {
            get {
                object obj = ResourceManager.GetObject("Dryad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DyeTrader {
            get {
                object obj = ResourceManager.GetObject("DyeTrader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EbonwoodChest {
            get {
                object obj = ResourceManager.GetObject("EbonwoodChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Emerald {
            get {
                object obj = ResourceManager.GetObject("Emerald", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FrozenChest {
            get {
                object obj = ResourceManager.GetObject("FrozenChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gems {
            get {
                object obj = ResourceManager.GetObject("Gems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoblinTinkerer {
            get {
                object obj = ResourceManager.GetObject("GoblinTinkerer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gold {
            get {
                object obj = ResourceManager.GetObject("Gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoldCache {
            get {
                object obj = ResourceManager.GetObject("GoldCache", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoldChest {
            get {
                object obj = ResourceManager.GetObject("GoldChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Guide {
            get {
                object obj = ResourceManager.GetObject("Guide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HallowedChest {
            get {
                object obj = ResourceManager.GetObject("HallowedChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Heart {
            get {
                object obj = ResourceManager.GetObject("Heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HeartFruit {
            get {
                object obj = ResourceManager.GetObject("HeartFruit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hellforge {
            get {
                object obj = ResourceManager.GetObject("Hellforge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hellstone {
            get {
                object obj = ResourceManager.GetObject("Hellstone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IceChest {
            get {
                object obj = ResourceManager.GetObject("IceChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Iron {
            get {
                object obj = ResourceManager.GetObject("Iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;data&gt;
        ///  &lt;tiles&gt;
        ///    &lt;tile name=&quot;Dirt&quot; tileImage=&quot;0&quot; autoGenType=&quot;Building Block&quot; color=&quot;#AF8365&quot; officialColor=&quot;#976B4B&quot; /&gt;
        ///    &lt;tile name=&quot;Stone&quot; tileImage=&quot;1&quot; autoGenType=&quot;Ore Blend&quot; color=&quot;#808080&quot; officialColor=&quot;#808080&quot; /&gt;
        ///    &lt;tile name=&quot;Grass&quot; tileImage=&quot;2&quot; autoGenType=&quot;Grass Blend&quot; color=&quot;#1CD85E&quot; officialColor=&quot;#1CD85E&quot; /&gt;
        ///    &lt;tile name=&quot;Plants&quot; tileImage=&quot;3&quot; color=&quot;Plants&quot; officialColor=&quot;#1AC454&quot; /&gt;
        ///    &lt;tile name=&quot;Torch&quot; tileImage=&quot;4&quot; color=&quot;Light  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap IvyChest {
            get {
                object obj = ResourceManager.GetObject("IvyChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JungleChest {
            get {
                object obj = ResourceManager.GetObject("JungleChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lead {
            get {
                object obj = ResourceManager.GetObject("Lead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LihzahrdChest {
            get {
                object obj = ResourceManager.GetObject("LihzahrdChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LivingWoodChest {
            get {
                object obj = ResourceManager.GetObject("LivingWoodChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedCorruptionChest {
            get {
                object obj = ResourceManager.GetObject("LockedCorruptionChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedCrimsonChest {
            get {
                object obj = ResourceManager.GetObject("LockedCrimsonChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedFrozenChest {
            get {
                object obj = ResourceManager.GetObject("LockedFrozenChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedGoldChest {
            get {
                object obj = ResourceManager.GetObject("LockedGoldChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedHallowedChest {
            get {
                object obj = ResourceManager.GetObject("LockedHallowedChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedJungleChest {
            get {
                object obj = ResourceManager.GetObject("LockedJungleChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LockedShadowChest {
            get {
                object obj = ResourceManager.GetObject("LockedShadowChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mechanic {
            get {
                object obj = ResourceManager.GetObject("Mechanic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Merchant {
            get {
                object obj = ResourceManager.GetObject("Merchant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Meteorite {
            get {
                object obj = ResourceManager.GetObject("Meteorite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mythril {
            get {
                object obj = ResourceManager.GetObject("Mythril", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nurse {
            get {
                object obj = ResourceManager.GetObject("Nurse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Objects {
            get {
                object obj = ResourceManager.GetObject("Objects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Obsidian {
            get {
                object obj = ResourceManager.GetObject("Obsidian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OldMan {
            get {
                object obj = ResourceManager.GetObject("OldMan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ores {
            get {
                object obj = ResourceManager.GetObject("Ores", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Orichalcum {
            get {
                object obj = ResourceManager.GetObject("Orichalcum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Painter {
            get {
                object obj = ResourceManager.GetObject("Painter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Palladium {
            get {
                object obj = ResourceManager.GetObject("Palladium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartyGirl {
            get {
                object obj = ResourceManager.GetObject("PartyGirl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PearlwoodChest {
            get {
                object obj = ResourceManager.GetObject("PearlwoodChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Picture {
            get {
                object obj = ResourceManager.GetObject("Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pirate {
            get {
                object obj = ResourceManager.GetObject("Pirate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlanteraBulb {
            get {
                object obj = ResourceManager.GetObject("PlanteraBulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Platinum {
            get {
                object obj = ResourceManager.GetObject("Platinum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RichMahoganyChest {
            get {
                object obj = ResourceManager.GetObject("RichMahoganyChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ruby {
            get {
                object obj = ResourceManager.GetObject("Ruby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SantaClaus {
            get {
                object obj = ResourceManager.GetObject("SantaClaus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sapphire {
            get {
                object obj = ResourceManager.GetObject("Sapphire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShadewoodChest {
            get {
                object obj = ResourceManager.GetObject("ShadewoodChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShadowChest {
            get {
                object obj = ResourceManager.GetObject("ShadowChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShadowOrb {
            get {
                object obj = ResourceManager.GetObject("ShadowOrb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sign {
            get {
                object obj = ResourceManager.GetObject("Sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Silver {
            get {
                object obj = ResourceManager.GetObject("Silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkywareChest {
            get {
                object obj = ResourceManager.GetObject("SkywareChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spawn {
            get {
                object obj = ResourceManager.GetObject("Spawn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Statue {
            get {
                object obj = ResourceManager.GetObject("Statue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Steampunker {
            get {
                object obj = ResourceManager.GetObject("Steampunker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tin {
            get {
                object obj = ResourceManager.GetObject("Tin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Titanium {
            get {
                object obj = ResourceManager.GetObject("Titanium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tombstone {
            get {
                object obj = ResourceManager.GetObject("Tombstone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Topaz {
            get {
                object obj = ResourceManager.GetObject("Topaz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Torch {
            get {
                object obj = ResourceManager.GetObject("Torch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TrashCan {
            get {
                object obj = ResourceManager.GetObject("TrashCan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Truffle {
            get {
                object obj = ResourceManager.GetObject("Truffle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tungsten {
            get {
                object obj = ResourceManager.GetObject("Tungsten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unknown {
            get {
                object obj = ResourceManager.GetObject("Unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WaterChest {
            get {
                object obj = ResourceManager.GetObject("WaterChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WebCoveredChest {
            get {
                object obj = ResourceManager.GetObject("WebCoveredChest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WitchDoctor {
            get {
                object obj = ResourceManager.GetObject("WitchDoctor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wizard {
            get {
                object obj = ResourceManager.GetObject("Wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
