namespace TerrariaWorldViewer
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    public enum TileType
    {
        Dirt,
        Stone,
        Grass,
        Plants,
        Torches,
        Trees,
        Iron,
        Copper,
        Gold,
        Silver,
        Door1,
        Door2,
        Heart,
        Bottles,
        Table,
        Chair,
        Anvil,
        Furnance,
        CraftingTable,
        WoodenPlatform,
        PlantsDecorative,
        Chest,
        CorruptionStone1,
        CorruptionGrass,
        CorruptionPlants,
        CorruptionStone2,
        Altar,
        Sunflower,
        Pot,
        PiggyBank,
        BlockWood,
        ShadowOrb,
        CorruptionVines,
        Candle,
        ChandlerCopper,
        ChandlerSilver,
        ChandlerGold,
        Meterorite, // Credit Vib Rib
        BlockStone,
        BlockRedStone,
        Clay,
        BlockBlueStone,
        LightGlobe,
        BlockGreenStone,
        BlockPinkStone,
        BlockGold,
        BlockSilver,
        BlockCopper,
        Spikes,
        CandleBlue,
        Books,
        Web,
        Vines,
        Sand,
        Glass,
        Signs,
        Obsidian,
        Ash, // Credit Infinite Monkeys
        Hellstone, // Credit Vib Rib
        Mud,
        UndergroundJungleGrass,
        UndergroundJunglePlants,
        UndergroundJungleVines,
        Sapphire,
        Ruby,
        Emerald,
        Topaz,
        Amethyst,
        Diamond,
        UndergroundJungleThorns, // Credit Dr VideoGames 0031
        UndergroundMushroomGrass,
        UndergroundMushroomPlants,
        UndergroundMushroomTrees,
        Plants2,
        Plants3,
        BlockObsidian,
        BlockHellstone,
        UnderworldFurnance,
        DecorativePot,
        Bed,
        Unknown,

        // Additonal Placed Out of range of byte
        Spawn = 255,
        Sky = 256,
        Water = 257,
        Lava = 258,

        WallStone = 259,
        WallDirt,
        WallStone2,
        WallWood,
        WallBrick,
        WallRed,
        WallBlue,
        WallGreen,
        WallPink,
        WallGold,
        WallSilver,
        WallCopper,
        WallHellstone,
        WallBackground,
    }

}
